/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class aiMetadata : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal aiMetadata(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(aiMetadata obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~aiMetadata() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_aiMetadata(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint mNumProperties {
    set {
      AssimpPINVOKE.aiMetadata_mNumProperties_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.aiMetadata_mNumProperties_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiString mKeys {
    set {
      AssimpPINVOKE.aiMetadata_mKeys_set(swigCPtr, SWIGTYPE_p_p_aiString.getCPtr(value));
    } 
    get {
      IntPtr cPtr = AssimpPINVOKE.aiMetadata_mKeys_get(swigCPtr);
      SWIGTYPE_p_p_aiString ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiString(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiString mValues {
    set {
      AssimpPINVOKE.aiMetadata_mValues_set(swigCPtr, SWIGTYPE_p_p_aiString.getCPtr(value));
    } 
    get {
      IntPtr cPtr = AssimpPINVOKE.aiMetadata_mValues_get(swigCPtr);
      SWIGTYPE_p_p_aiString ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiString(cPtr, false);
      return ret;
    } 
  }

  public aiMetadata() : this(AssimpPINVOKE.new_aiMetadata(), true) {
  }

  public bool Get(aiString key, aiString value) {
    bool ret = AssimpPINVOKE.aiMetadata_Get(swigCPtr, aiString.getCPtr(key), aiString.getCPtr(value));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
